# Block RAM IP Core for basys3_test
# Generated by build_rom_65c02.sh

create_ip -name blk_mem_gen -vendor xilinx.com -library ip -version 8.4 -module_name basys3_test_bram

set_property -dict [list \
    CONFIG.Memory_Type {Single_Port_ROM} \
    CONFIG.Port_A_Write_Rate {0} \
    CONFIG.Write_Width_A {8} \
    CONFIG.Read_Width_A {8} \
    CONFIG.Write_Depth_A {8192} \
    CONFIG.Enable_A {Always_Enabled} \
    CONFIG.Load_Init_File {true} \
    CONFIG.Coe_File {C:\Mac\Home\Storage\Dev\Vivado\sar6502\sar6502.srcs\sources_1\new\basys3_test.coe} \
    CONFIG.Fill_Remaining_Memory_Locations {true} \
    CONFIG.Remaining_Memory_Locations {00} \

] [get_ips basys3_test_bram]

generate_target all [get_ips]
